# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble

  Test:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew test
      
    - uses: actions/upload-artifact@v2
      with:
        name: testReport
        path: build/reports
    
      
  Assemble:
    needs: Test
    runs-on: ubuntu-latest
    outputs:
      get_version_: ${{ steps.get_version.outputs.version_ }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - id: get_version
      run: echo "::set-output name=version_::$(cat build.gradle | grep version | cut -d "'" -f 2)"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
      
    - uses: actions/upload-artifact@v2
      with:
        name: buildJar
        path: build/libs/*.jar

  Release:
    needs: Assemble
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: buildJar
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: buildJar/st_nycu_lab4-${{needs.Assemble.outputs.get_version_}}.jar
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
